### ISSUE TITLE
Is it possible to use non base editor image?

### ISSUE THREAD

**Issue by lvgrecords** [game-ci/unity-request-activation-file#57]
I'm trying to use `unityci/editor:2020.1.17f1-ios-0.7.0` but getting an error below:

```
Run webbertakken/unity-request-manual-activation-file@v2.0-alpha-1
/usr/bin/docker build /home/lvg/actions-runner/_work/_actions/webbertakken/unity-request-manual-activation-file/v2.0-alpha-1/action --file /home/lvg/actions-runner/_work/_actions/webbertakken/unity-request-manual-activation-file/v2.0-alpha-1/action/Dockerfile --build-arg IMAGE=unityci/editor:2020.1.17f1-ios-0.7.0-base-0 --tag unity-action:2020.1.17f1-ios-0.7.0-base-0
Sending build context to Docker daemon  133.1kB

Step 1/12 : ARG IMAGE
Step 2/12 : FROM $IMAGE
manifest for unityci/editor:2020.1.17f1-ios-0.7.0-base-0 not found: manifest unknown: manifest unknown
Error: The process '/usr/bin/docker' failed with exit code 1
```

My workflow:
```
name: Continuous Integration

on:
  pull_request: { }
  push: { branches: [ master ] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2020.1.17f1-ios-0.7.0

jobs:
  activation:
    name: Request manual activation file 🔑
    #    runs-on: ubuntu-20.04
    runs-on: self-hosted
    if: false #enable this job to request a manual unity license
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Request manual activation file
        uses: webbertakken/unity-request-manual-activation-file@v2.0-alpha-1
        id: getManualLicenseFile
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
      #          This will produce a Unity_xxx.alf file
      #          download it in your computer and upload it to
      #          https://license.unity3d.com/manual
      #          That will produce a Unity_xxx.ulf file
      #          add the contents of Unity_xxx.ulf file to your repository's secrets
      #          as UNITY_LICENSE
      #          then disable this job
```

Looks `-base-0` is added on runtime. Are there ability to use editor+modules based docker images eg `unityci/editor:2020.1.17f1-ios-0.7.0`?
In case it's not supported at that moment I do not mind to add such support myself by PR
